/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analysis/affected-properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Affected Properties
         * @description Fastigheter inom påverkansradien för matchande projekt.
         *
         *     Varje fastighet får listan över påverkande projekt med avstånd i meter.
         */
        get: operations["affected_properties_api_v1_analysis_affected_properties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/proximity-scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proximity Scores
         * @description Närhetspoäng: fastigheter rankade efter närhet till infrastruktur.
         *
         *     Poängen är summan av viktade bidrag (typ, status, avstånd, budget,
         *     tid till färdigställande) från projekt inom sökradien — varje bidrag
         *     redovisas för sig så att rankningen alltid går att förklara.
         */
        get: operations["proximity_scores_api_v1_analysis_proximity_scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Hälsokontroll som även verifierar databasanslutningen.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infrastructure/impact-zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Impact Zones
         * @description Påverkanszoner: projektgeometrier buffrade med sin påverkansradie i meter.
         *
         *     Beräknas i PostGIS över geography, vilket ger korrekta zoner för
         *     punkter, linjer och ytor oavsett latitud.
         */
        get: operations["impact_zones_api_v1_infrastructure_impact_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infrastructure/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Infrastrukturprojekt som GeoJSON FeatureCollection, med filter och paginering.
         */
        get: operations["list_projects_api_v1_infrastructure_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_infrastructure_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infrastructure/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_infrastructure_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infrastructure/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Registrerade externa datakällor (namn → visningsnamn).
         */
        get: operations["list_sources_api_v1_infrastructure_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infrastructure/sync/{source_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Source
         * @description Synkronisera en registrerad datakälla till databasen (upsert).
         */
        post: operations["sync_source_api_v1_infrastructure_sync__source_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Properties
         * @description Fastigheter som GeoJSON FeatureCollection, med filter och paginering.
         */
        get: operations["list_properties_api_v1_properties_get"];
        put?: never;
        /** Create Property */
        post: operations["create_property_api_v1_properties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Properties
         * @description Fritextsök på beteckning, adress, ägare, stad och kommun.
         */
        get: operations["search_properties_api_v1_properties_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Property */
        get: operations["get_property_api_v1_properties__property_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}/nearby-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nearby Projects
         * @description Infrastrukturprojekt nära en fastighet, närmast först (ST_DWithin).
         */
        get: operations["nearby_projects_api_v1_properties__property_id__nearby_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AffectedPropertiesCollection */
        AffectedPropertiesCollection: {
            /** Features */
            features?: components["schemas"]["AffectedPropertyFeature"][];
            /** Numbermatched */
            numberMatched: number;
            /** Numberreturned */
            numberReturned: number;
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /** AffectedPropertyFeature */
        AffectedPropertyFeature: {
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            properties: components["schemas"]["AffectedPropertyProps"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /** AffectedPropertyProps */
        AffectedPropertyProps: {
            /** Address */
            address?: string | null;
            /** Affecting Projects */
            affecting_projects?: components["schemas"]["AffectingProject"][];
            /** Area Sqm */
            area_sqm?: number | null;
            /** Assessed Value Sek */
            assessed_value_sek?: number | null;
            /** Building Year */
            building_year?: number | null;
            /** City */
            city?: string | null;
            /** County */
            county?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Designation */
            designation: string;
            /** Id */
            id: number;
            /** Living Area Sqm */
            living_area_sqm?: number | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            };
            /** Municipality */
            municipality?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Owner Org Number */
            owner_org_number?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            property_type?: components["schemas"]["PropertyType"] | null;
            /** Updated At */
            updated_at?: string | null;
            /** Zoning */
            zoning?: string | null;
        };
        /**
         * AffectingProject
         * @description Kompakt referens till ett projekt som påverkar en fastighet.
         */
        AffectingProject: {
            /** Distance M */
            distance_m: number;
            /** Name */
            name: string;
            /** Project Id */
            project_id: number;
            project_type?: components["schemas"]["ProjectType"] | null;
            status?: components["schemas"]["ProjectStatus"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Database
             * @default ok
             * @constant
             */
            database: "ok";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** ImpactZoneCollection */
        ImpactZoneCollection: {
            /** Features */
            features?: components["schemas"]["ImpactZoneFeature"][];
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /** ImpactZoneFeature */
        ImpactZoneFeature: {
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            properties: components["schemas"]["ImpactZoneProps"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /**
         * ImpactZoneProps
         * @description Egenskaper för en serverberäknad påverkanszon (buffrad projektgeometri).
         */
        ImpactZoneProps: {
            /** End Date */
            end_date?: string | null;
            /** Impact Radius M */
            impact_radius_m: number;
            /** Name */
            name: string;
            /** Project Id */
            project_id: number;
            project_type?: components["schemas"]["ProjectType"] | null;
            /** Start Date */
            start_date?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
        };
        /** InfrastructureProjectCollection */
        InfrastructureProjectCollection: {
            /** Features */
            features?: components["schemas"]["InfrastructureProjectFeature"][];
            /**
             * Numbermatched
             * @description Totalt antal träffar för frågan
             */
            numberMatched: number;
            /**
             * Numberreturned
             * @description Antal features i detta svar
             */
            numberReturned: number;
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /** InfrastructureProjectCreate */
        InfrastructureProjectCreate: {
            /** Budget Sek */
            budget_sek?: number | null;
            /** Description */
            description?: string | null;
            /** End Date */
            end_date?: string | null;
            /** External Id */
            external_id?: string | null;
            /**
             * Geometry
             * @description GeoJSON-geometri i WGS84
             */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /**
             * Impact Radius M
             * @default 1000
             */
            impact_radius_m: number;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            project_type?: components["schemas"]["ProjectType"] | null;
            /**
             * Source
             * @default manual
             */
            source: string;
            /** Start Date */
            start_date?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
        };
        /** InfrastructureProjectFeature */
        InfrastructureProjectFeature: {
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            properties: components["schemas"]["InfrastructureProjectProps"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /** InfrastructureProjectProps */
        InfrastructureProjectProps: {
            /** Budget Sek */
            budget_sek?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Description */
            description?: string | null;
            /** End Date */
            end_date?: string | null;
            /** External Id */
            external_id?: string | null;
            /** Id */
            id: number;
            /**
             * Impact Radius M
             * @default 1000
             */
            impact_radius_m: number;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            project_type?: components["schemas"]["ProjectType"] | null;
            /**
             * Source
             * @default manual
             */
            source: string;
            /** Start Date */
            start_date?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * NearbyProject
         * @description Ett infrastrukturprojekt i närheten av en fastighet.
         */
        NearbyProject: {
            /**
             * Distance M
             * @description Avstånd i meter från fastigheten till projektet
             */
            distance_m: number;
            project: components["schemas"]["InfrastructureProjectProps"];
            /**
             * Within Impact Radius
             * @description Om fastigheten ligger inom projektets påverkansradie
             */
            within_impact_radius: boolean;
        };
        /** NearbyProjectsResponse */
        NearbyProjectsResponse: {
            /** Max Distance M */
            max_distance_m: number;
            /** Projects */
            projects?: components["schemas"]["NearbyProject"][];
            /** Property Id */
            property_id: number;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "planerad" | "pågående" | "avslutad";
        /**
         * ProjectType
         * @enum {string}
         */
        ProjectType: "väg" | "järnväg" | "kollektivtrafik" | "bro" | "tunnel" | "cykelväg" | "övrigt";
        /** PropertyCollection */
        PropertyCollection: {
            /** Features */
            features?: components["schemas"]["PropertyFeature"][];
            /**
             * Numbermatched
             * @description Totalt antal träffar för frågan
             */
            numberMatched: number;
            /**
             * Numberreturned
             * @description Antal features i detta svar
             */
            numberReturned: number;
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /** PropertyCreate */
        PropertyCreate: {
            /** Address */
            address?: string | null;
            /** Area Sqm */
            area_sqm?: number | null;
            /** Assessed Value Sek */
            assessed_value_sek?: number | null;
            /** Building Year */
            building_year?: number | null;
            /** City */
            city?: string | null;
            /** County */
            county?: string | null;
            /** Designation */
            designation: string;
            /**
             * Geometry
             * @description GeoJSON-geometri (Polygon eller MultiPolygon) i WGS84
             */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /** Living Area Sqm */
            living_area_sqm?: number | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            };
            /** Municipality */
            municipality?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Owner Org Number */
            owner_org_number?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            property_type?: components["schemas"]["PropertyType"] | null;
            /** Zoning */
            zoning?: string | null;
        };
        /** PropertyFeature */
        PropertyFeature: {
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            properties: components["schemas"]["PropertyProps"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /** PropertyProps */
        PropertyProps: {
            /** Address */
            address?: string | null;
            /** Area Sqm */
            area_sqm?: number | null;
            /** Assessed Value Sek */
            assessed_value_sek?: number | null;
            /** Building Year */
            building_year?: number | null;
            /** City */
            city?: string | null;
            /** County */
            county?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Designation */
            designation: string;
            /** Id */
            id: number;
            /** Living Area Sqm */
            living_area_sqm?: number | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            };
            /** Municipality */
            municipality?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Owner Org Number */
            owner_org_number?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            property_type?: components["schemas"]["PropertyType"] | null;
            /** Updated At */
            updated_at?: string | null;
            /** Zoning */
            zoning?: string | null;
        };
        /**
         * PropertyType
         * @enum {string}
         */
        PropertyType: "bostad" | "kontor" | "handel" | "industri" | "utbildning" | "villa";
        /** ProximityScoreFeature */
        ProximityScoreFeature: {
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            properties: components["schemas"]["ProximityScoreProps"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /** ProximityScoreProps */
        ProximityScoreProps: {
            /** Address */
            address?: string | null;
            /** Area Sqm */
            area_sqm?: number | null;
            /** Assessed Value Sek */
            assessed_value_sek?: number | null;
            /** Building Year */
            building_year?: number | null;
            /** City */
            city?: string | null;
            /**
             * Contributions
             * @description Bidragen bakom poängen, största först
             */
            contributions?: components["schemas"]["ScoreContribution"][];
            /** County */
            county?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Designation */
            designation: string;
            /** Id */
            id: number;
            /** Living Area Sqm */
            living_area_sqm?: number | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            };
            /** Municipality */
            municipality?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Owner Org Number */
            owner_org_number?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            property_type?: components["schemas"]["PropertyType"] | null;
            /**
             * Rank
             * @description 1 = högst poäng i svaret
             */
            rank: number;
            /**
             * Score
             * @description Summan av alla projektbidrag — högre är bättre läge
             */
            score: number;
            /** Updated At */
            updated_at?: string | null;
            /** Zoning */
            zoning?: string | null;
        };
        /** ProximityScoresCollection */
        ProximityScoresCollection: {
            /**
             * Features
             * @description Sorterade efter poäng, högst först
             */
            features?: components["schemas"]["ProximityScoreFeature"][];
            /**
             * Max Distance M
             * @description Sökradien som poängen beräknats med
             */
            max_distance_m: number;
            /** Numbermatched */
            numberMatched: number;
            /** Numberreturned */
            numberReturned: number;
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /**
         * ScoreContribution
         * @description Ett enskilt projekts bidrag till en fastighets närhetspoäng.
         */
        ScoreContribution: {
            /** Distance M */
            distance_m: number;
            /** Name */
            name: string;
            /** Points */
            points: number;
            /** Project Id */
            project_id: number;
            project_type?: components["schemas"]["ProjectType"] | null;
            status?: components["schemas"]["ProjectStatus"] | null;
        };
        /**
         * SyncResult
         * @description Resultatet av en synkronisering mot en extern datakälla.
         */
        SyncResult: {
            /**
             * Fetched
             * @description Antal objekt som datakällan levererade
             */
            fetched: number;
            /**
             * Skipped
             * @description Antal objekt som hoppades över (t.ex. ogiltig geometri)
             */
            skipped: number;
            /** Source */
            source: string;
            /**
             * Truncated
             * @description true om källan inte kunde hämta allt (sidgräns nådd) — kör synken igen
             * @default false
             */
            truncated: boolean;
            /**
             * Upserted
             * @description Antal objekt som skapades eller uppdaterades
             */
            upserted: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    affected_properties_api_v1_analysis_affected_properties_get: {
        parameters: {
            query?: {
                /** @description Begränsa till projekt med dessa statusar */
                status?: components["schemas"]["ProjectStatus"][] | null;
                /** @description Begränsa till projekt av dessa typer */
                project_type?: components["schemas"]["ProjectType"][] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AffectedPropertiesCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proximity_scores_api_v1_analysis_proximity_scores_get: {
        parameters: {
            query?: {
                /** @description Räkna bara projekt med dessa statusar */
                status?: components["schemas"]["ProjectStatus"][] | null;
                /** @description Räkna bara projekt av dessa typer */
                project_type?: components["schemas"]["ProjectType"][] | null;
                /** @description Räkna bara projekt aktiva under detta år */
                year?: number | null;
                /** @description Sökradie i meter */
                max_distance_m?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProximityScoresCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    impact_zones_api_v1_infrastructure_impact_zones_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProjectStatus"][] | null;
                project_type?: components["schemas"]["ProjectType"][] | null;
                /** @description Visa bara projekt som är aktiva under detta år */
                year?: number | null;
                /** @description Avgränsningsruta i WGS84: väst,syd,öst,norr */
                bbox?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactZoneCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_infrastructure_projects_get: {
        parameters: {
            query?: {
                /** @description Filtrera på status (kan upprepas) */
                status?: components["schemas"]["ProjectStatus"][] | null;
                /** @description Filtrera på projekttyp (kan upprepas) */
                project_type?: components["schemas"]["ProjectType"][] | null;
                /** @description Visa bara projekt som är aktiva under detta år */
                year?: number | null;
                limit?: number;
                offset?: number;
                /** @description Avgränsningsruta i WGS84: väst,syd,öst,norr */
                bbox?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfrastructureProjectCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_infrastructure_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InfrastructureProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfrastructureProjectFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_infrastructure_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfrastructureProjectFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_infrastructure_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    sync_source_api_v1_infrastructure_sync__source_name__post: {
        parameters: {
            query?: {
                /** @description Avgränsningsruta i WGS84: väst,syd,öst,norr */
                bbox?: string | null;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                source_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_properties_api_v1_properties_get: {
        parameters: {
            query?: {
                /** @description Filtrera på kommun (kan upprepas) */
                municipality?: string[] | null;
                /** @description Filtrera på fastighetstyp (kan upprepas) */
                property_type?: components["schemas"]["PropertyType"][] | null;
                /** @description Lägsta taxeringsvärde (SEK) */
                min_value?: number | null;
                /** @description Högsta taxeringsvärde (SEK) */
                max_value?: number | null;
                limit?: number;
                offset?: number;
                /** @description Avgränsningsruta i WGS84: väst,syd,öst,norr */
                bbox?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_property_api_v1_properties_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_properties_api_v1_properties_search_get: {
        parameters: {
            query: {
                /** @description Sökterm */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_property_api_v1_properties__property_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nearby_projects_api_v1_properties__property_id__nearby_projects_get: {
        parameters: {
            query?: {
                /** @description Maximalt avstånd i meter */
                max_distance_m?: number;
            };
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
