from app.schemas.analysis import (
    AffectedPropertiesCollection,
    AffectedPropertyFeature,
    AffectedPropertyProps,
    AffectingProject,
    NearbyProject,
    NearbyProjectsResponse,
    ProximityScoreFeature,
    ProximityScoreProps,
    ProximityScoresCollection,
    ScoreContribution,
)
from app.schemas.common import GeoJSONGeometry, HealthStatus, SyncResult
from app.schemas.demographics import DesoAreaCollection, DesoAreaFeature, DesoAreaProps
from app.schemas.infrastructure import (
    ImpactZoneCollection,
    ImpactZoneFeature,
    ImpactZoneProps,
    InfrastructureProjectCollection,
    InfrastructureProjectCreate,
    InfrastructureProjectFeature,
    InfrastructureProjectProps,
)
from app.schemas.planning import DetailPlanCollection, DetailPlanFeature, DetailPlanProps
from app.schemas.property import (
    PropertyCollection,
    PropertyCreate,
    PropertyFeature,
    PropertyProps,
)
from app.schemas.watch import (
    DetailPlanWatchEvent,
    ProjectWatchEvent,
    WatchedAreaCollection,
    WatchedAreaCreate,
    WatchedAreaFeature,
    WatchedAreaProps,
    WatchEvents,
    WatchEventsResponse,
)

__all__ = [
    "AffectedPropertiesCollection",
    "AffectedPropertyFeature",
    "AffectedPropertyProps",
    "AffectingProject",
    "DesoAreaCollection",
    "DesoAreaFeature",
    "DesoAreaProps",
    "DetailPlanCollection",
    "DetailPlanFeature",
    "DetailPlanProps",
    "DetailPlanWatchEvent",
    "GeoJSONGeometry",
    "HealthStatus",
    "ImpactZoneCollection",
    "ImpactZoneFeature",
    "ImpactZoneProps",
    "InfrastructureProjectCollection",
    "InfrastructureProjectCreate",
    "InfrastructureProjectFeature",
    "InfrastructureProjectProps",
    "NearbyProject",
    "NearbyProjectsResponse",
    "ProjectWatchEvent",
    "PropertyCollection",
    "PropertyCreate",
    "PropertyFeature",
    "PropertyProps",
    "ProximityScoreFeature",
    "ProximityScoreProps",
    "ProximityScoresCollection",
    "ScoreContribution",
    "SyncResult",
    "WatchEvents",
    "WatchEventsResponse",
    "WatchedAreaCollection",
    "WatchedAreaCreate",
    "WatchedAreaFeature",
    "WatchedAreaProps",
]
